name: telegram_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  file_picker: ^8.3.2
  shared_preferences: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/telegram_logo.png
    - assets/background.png


  